### ISSUE TITLE
Deprecated inkscape option stops compilation

### ISSUE THREAD

**Issue by gibuday** [dominique-unruh/mathquill-for-gmail#18]
Dear @dominique-unruh  

I tried to compile your package for using it with Thunderbird on Windows.

After making inkscape available for my git bash, running make resulted in
```
SIZE=icon-32.png; SIZE="${SIZE%.png}"; SIZE="${SIZE#icon-}"; \
  inkscape --export-png=icon-32.png --export-background-opacity=0 -w "$SIZE" --without-gui icon.svg
Warning: Option --export-png= is deprecated
Warning: Option --without-gui= is deprecated
Unknown option --export-png=icon-32.png
make: *** [Makefile:8: icon-32.png] Error 1
```

I have 
```
$ inkscape --version
Inkscape 1.1.1 (3bf5ae0d25, 2021-09-20)
```
What do you suggest to make it work?

**Comment by gibuday** [comment]
https://stackoverflow.com/questions/34725801/converting-svg-to-png-with-inkscape-command-line-failing/69891398#69891398

tells the new syntax:
```
$ inkscape --export-type="png" myfile.svg --export-filename=myfile.png
```
which made it work when I put it into the Makefile

**Comment by dominique-unruh** [comment]
Yes, I just found the same syntax independently...

Interestingly enough, on my system (`Inkscape 1.2.1 (9c6d41e410, 2022-07-14, custom)`), the old command line still works and only gives the warnings but not the error.

In any case, now it should be better.

**Comment by gibuday** [comment]
Also: the 
```
--without-gui
```
was deprecated as well, I removed it and the compilation worked through.
