### ISSUE TITLE
Ctrl-M is captured by Windows

### ISSUE THREAD

**Issue by gibuday** [dominique-unruh/mathquill-for-gmail#19]
I compiled Mathquill from sources on Windows. I installed the zip package to Thunderbird.

MathQuill appears on the toolbar on Thunderbird. When I try to activate it, seemingly nothing happens.

When I start to compose a mail, I click on CTRL-M as suggested, but no formula editor comes up but Windows captures this hotkey and gives focus to another window.

From this, do you have an idea what is missing? @dominique-unruh

**Comment by dominique-unruh** [comment]
By "Windows captures this hotkey and gives focus to another window" do you mean a new Thunderbird compose window is opened? Or something else happens?

**Comment by dominique-unruh** [comment]
I tried to reproduce the error (Windows 11, Thunderbird 102.3.0 (64-bit), start writing a new email, go to the text area for the message body, type ctrl-m), and I got the formula editor (a little box appears and typing edits the formula).

The MathQuill button in the message list view is not needed for this. ("Activate" is only useful for the web-version of the extension.)

Maybe ctrl-m is bound to something else on your system. You can try changing the hotkey to something else in the extension settings:

![image](https://user-images.githubusercontent.com/9913676/192507309-6f5d9964-0ec5-4b1b-baec-9f36c4aa881e.png)

I will close the issue but if you have any extra information (e.g., how to reproduce the bug), please let me know.
